### ISSUE TITLE
Output user name from store

### ISSUE THREAD

**Issue by deljus** [meow-org/chat-server#19]
<img width="357" alt="Screen Shot 2020-02-20 at 16 44 02" src="https://user-images.githubusercontent.com/25724645/74939686-5ff7d780-5401-11ea-8090-bf85faed59df.png">
<img width="375" alt="Screen Shot 2020-02-20 at 16 44 10" src="https://user-images.githubusercontent.com/25724645/74939688-61c19b00-5401-11ea-9453-c83130445336.png">
<img width="1334" alt="Screen Shot 2020-02-20 at 16 44 19" src="https://user-images.githubusercontent.com/25724645/74939691-62f2c800-5401-11ea-8b4c-b65b4e94e736.png">

**Comment by VladimirGorbachuk** [comment]
I've completed the given task. Amendments to code were kept minimal
